### ISSUE TITLE
prettier 3.4.x broke this package

### ISSUE THREAD

**Issue by dez1729** [ony3000/prettier-plugin-brace-style#43]
The brace styles other than default is broken after updating prettier to 3.4.0 or later. It will return errors when trying to format.

## Steps to reproduce
1. Update prettier to 3.4.0 or later
2. Restart IDE.
3. Run prettier (or save if run on save)

## The current behavior
Prettier will no longer format as the plugin is breaking the run.

## The expected behavior
Prettier should format the page, with the selected brace style.

**Comment by ony3000** [comment]
That's strange. I can't reproduce this issue.

All tests pass and formatting in VS Code works as expected.

Can you provide more details?

**Comment by dez1729** [comment]
This was what it was trying to parse:
![image](https://github.com/user-attachments/assets/d487522a-4f5e-4c3e-a7da-e1b84af7edf8)
and this is the output when formatting:
![image](https://github.com/user-attachments/assets/d437c87f-ef58-49a5-941e-632d3fd284f0)

**Comment by ony3000** [comment]
@dez1729 Fixed in `v0.7.1`, check it out!
