### ISSUE TITLE
Format array of objects

### ISSUE THREAD

**Issue by fast-facts** [ony3000/prettier-plugin-brace-style#7]
## Is your feature request related to a problem? Please describe

Could this be also applied to array of objects, like the below?

```
  await func(
    {
      a: '',
      b: '',
    },
    {
      a: '',
      b: '',
    }
  );
```

## Describe the solution you'd like

In `1tbs`, it should look like 

```
  await func({
    a: '',
    b: '',
  }, {
    a: '',
    b: '',
  });
```

and like so in `allman`

```
  await func({
    a: '',
    b: '',
  }, 
  {
    a: '',
    b: '',
  });
```

**Comment by ony3000** [comment]
Unfortunately, this is difficult to support.

This plugin is theoretically equivalent to applying ESLint formatting (`brace-style` only) after applying Prettier formatting.
The code snippet you presented is considered error-free according to ESLint rules once Prettier formatting is applied, so it is difficult to set arbitrary rules.
